server:
  port: 55550
  servlet:
    context-path: /push

spring:
  application:
    name: lets-chat-push
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11110/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
